/* Copyright 1990-2008 Citrix Systems, Inc. */
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CtxSmcDlg.rc
//
#define IDD_DLG_MAIN                    101
#define IDD_DLG_SESSION                 102
#define IDD_DLG_VCHANNEL                103
#define IDD_DLG_OPTIONS                 104
#define IDD_DLG_CHANNEL                 105
#define IDI_ICON_CHANNEL                200
#define IDC_SESSION_DROP                1001
#define IDC_TAB_DATA                    1002
#define IDC_SRV_SENT_BEFORE             1100
#define IDC_SRV_SENT_AFTER              1101
#define IDC_SRV_SENT_AVE                1102
#define IDC_SRV_RECV_BEFORE             1103
#define IDC_SRV_RECV_AFTER              1104
#define IDC_SRV_RECV_AVE                1105
#define IDC_SESS_SENT_COUNT             1200
#define IDC_SESS_SENT_BW                1201
#define IDC_SESS_SENT_COMP              1202
#define IDC_SESS_RECV_COUNT             1203
#define IDC_SESS_RECV_BW                1204
#define IDC_SESS_RECV_COMP              1205
#define IDC_LATENCY_LAST                1206
#define IDC_LATENCY_LAST_COUNT          1207
#define IDC_LATENCY_AVE                 1208
#define IDC_LATENCY_AVE_COUNT           1209
#define IDC_LATENCY_TRIP                1210
#define IDC_LATENCY_TRIP_COUNT          1211
#define IDC_LATENCY_LAST_TIME           1212
#define IDC_SESS_OUTPUT_LS              1213
#define IDC_SESS_OUTPUT_COUNT           1214
#define IDC_SESS_INPUT_LS               1215
#define IDC_SESS_INPUT_COUNT            1216
#define IDC_SENT_BW_COUNT               1219
#define IDC_RECV_BW_COUNT               1220
#define IDC_OPT_REFRESH                 1500
#define IDC_OPT_REFRESH_COUNT           1501
#define IDC_OPT_BANDWIDTH               1502
#define IDC_OPT_BANDWIDTH_COUNT         1503
#define IDC_OPT_LATENCY                 1504
#define IDC_OPT_LATENCY_COUNT           1505
#define IDC_OPT_BW_LIMIT                1506
#define IDC_OPT_BW_LIMIT_COUNT          1507
#define IDC_CHANNEL_LABEL               1600
#define IDC_CHANNEL_FRIENDLY            1601
#define IDC_CHANNEL_CONTROL             1602
#define IDC_CHANNEL_CONTROL_COUNT       1603
#define IDC_CHANNEL_VERYHIGH            1604
#define IDC_CHANNEL_HIGH                1605
#define IDC_CHANNEL_NORMAL              1606
#define IDC_CHANNEL_LOW                 1607
#define IDC_SESSION_BWIDTH              1900
#define IDC_SESSION_LIMIT               1901
#define IDC_SESSION_LIMIT_COUNT         1902
#define IDC_VCHANNEL_BASE               2000
#define IDC_BUTTON_LPT1                 2000
#define IDC_BWIDTH_LPT1                 2001
#define IDC_PROGRESS_LPT1               2002
#define IDC_PRIORITY_LPT1               2003
#define IDC_BUTTON_LPT2                 2004
#define IDC_BWIDTH_LPT2                 2005
#define IDC_PROGRESS_LPT2               2006
#define IDC_PRIORITY_LPT2               2007
#define IDC_BUTTON_CPM                  2008
#define IDC_BWIDTH_CPM                  2009
#define IDC_PROGRESS_CPM                2010
#define IDC_PRIORITY_CPM                2011
#define IDC_BUTTON_COM1                 2012
#define IDC_BWIDTH_COM1                 2013
#define IDC_PROGRESS_COM1               2014
#define IDC_PRIORITY_COM1               2015
#define IDC_BUTTON_COM2                 2016
#define IDC_BWIDTH_COM2                 2017
#define IDC_PROGRESS_COM2               2018
#define IDC_PRIORITY_COM2               2019
#define IDC_BUTTON_CCM                  2020
#define IDC_BWIDTH_CCM                  2021
#define IDC_PROGRESS_CCM                2022
#define IDC_PRIORITY_CCM                2023
#define IDC_BUTTON_CDM                  2024
#define IDC_BWIDTH_CDM                  2025
#define IDC_PROGRESS_CDM                2026
#define IDC_PRIORITY_CDM                2027
#define IDC_BUTTON_CLIP                 2028
#define IDC_BWIDTH_CLIP                 2029
#define IDC_PROGRESS_CLIP               2030
#define IDC_PRIORITY_CLIP               2031
#define IDC_BUTTON_TW                   2032
#define IDC_BWIDTH_TW                   2033
#define IDC_PROGRESS_TW                 2034
#define IDC_PRIORITY_TW                 2035
#define IDC_BUTTON_TWI                  2036
#define IDC_BWIDTH_TWI                  2037
#define IDC_PROGRESS_TWI                2038
#define IDC_PRIORITY_TWI                2039
#define IDC_BUTTON_ZLFK                 2040
#define IDC_BWIDTH_ZLFK                 2041
#define IDC_PROGRESS_ZLFK               2042
#define IDC_PRIORITY_ZLFK               2043
#define IDC_BUTTON_ZLC                  2044
#define IDC_BWIDTH_ZLC                  2045
#define IDC_PROGRESS_ZLC                2046
#define IDC_PRIORITY_ZLC                2047
#define IDC_BUTTON_CTL                  2048
#define IDC_BWIDTH_CTL                  2049
#define IDC_PROGRESS_CTL                2050
#define IDC_PRIORITY_CTL                2051
#define IDC_BUTTON_PASS                 2052
#define IDC_BWIDTH_PASS                 2053
#define IDC_PROGRESS_PASS               2054
#define IDC_PRIORITY_PASS               2055
#define IDC_BUTTON_CAM                  2056
#define IDC_BWIDTH_CAM                  2057
#define IDC_PROGRESS_CAM                2058
#define IDC_PRIORITY_CAM                2059
#define IDC_BUTTON_CM                   2060
#define IDC_BWIDTH_CM                   2061
#define IDC_PROGRESS_CM                 2062
#define IDC_PRIORITY_CM                 2063
#define IDC_BUTTON_LIC                  2064
#define IDC_BWIDTH_LIC                  2065
#define IDC_PROGRESS_LIC                2066
#define IDC_PRIORITY_LIC                2067
#define IDC_BUTTON_VFM                  2068
#define IDC_BWIDTH_VFM                  2069
#define IDC_PROGRESS_VFM                2070
#define IDC_PRIORITY_VFM                2071
#define IDC_BUTTON_PN                   2072
#define IDC_BWIDTH_PN                   2073
#define IDC_PROGRESS_PN                 2074
#define IDC_PRIORITY_PN                 2075
#define IDC_BUTTON_SCRD                 2076
#define IDC_BWIDTH_SCRD                 2077
#define IDC_PROGRESS_SCRD               2078
#define IDC_PRIORITY_SCRD               2079
#define IDC_BUTTON_MM                   2080
#define IDC_BWIDTH_MM                   2081
#define IDC_PROGRESS_MM                 2082
#define IDC_PRIORITY_MM                 2083
#define IDC_BUTTON_SBR                  2084
#define IDC_BWIDTH_SBR                  2085
#define IDC_PROGRESS_SBR                2086
#define IDC_PRIORITY_SBR                2087
#define IDC_BUTTON_TWN                  2088
#define IDC_BWIDTH_TWN                  2089
#define IDC_PROGRESS_TWN                2090
#define IDC_PRIORITY_TWN                2091
#define IDC_BUTTON_OEM1                 2092
#define IDC_BWIDTH_OEM1                 2093
#define IDC_PROGRESS_OEM1               2094
#define IDC_PRIORITY_OEM1               2095
#define IDC_BUTTON_OEM2                 2096
#define IDC_BWIDTH_OEM2                 2097
#define IDC_PROGRESS_OEM2               2098
#define IDC_PRIORITY_OEM2               2099
#define IDC_BUTTON_OEM3                 2100
#define IDC_BWIDTH_OEM3                 2101
#define IDC_PROGRESS_OEM3               2102
#define IDC_PRIORITY_OEM3               2103
#define IDC_BUTTON_OEM4                 2104
#define IDC_BWIDTH_OEM4                 2105
#define IDC_PROGRESS_OEM4               2106
#define IDC_PRIORITY_OEM4               2107
#define IDC_BUTTON_OEM5                 2108
#define IDC_BWIDTH_OEM5                 2109
#define IDC_PROGRESS_OEM5               2110
#define IDC_PRIORITY_OEM5               2111
#define IDS_DESCR_BASE                  3000
#define IDS_DESCR_CTXLPT1               3000
#define IDS_DESCR_CTXLPT2               3001
#define IDS_DESCR_CTXCPM                3002
#define IDS_DESCR_CTXCOM1               3003
#define IDS_DESCR_CTXCOM2               3004
#define IDS_DESCR_CTXCCM                3005
#define IDS_DESCR_CTXCDM                3006
#define IDS_DESCR_CTXCLIP               3007
#define IDS_DESCR_CTXTW                 3008
#define IDS_DESCR_CTXTWI                3009
#define IDS_DESCR_CTXZLFK               3010
#define IDS_DESCR_CTXZLC                3011
#define IDS_DESCR_CTXCTL                3012
#define IDS_DESCR_CTXPASS               3013
#define IDS_DESCR_CTXCAM                3014
#define IDS_DESCR_CTXCM                 3015
#define IDS_DESCR_CTXLIC                3016
#define IDS_DESCR_CTXVFM                3017
#define IDS_DESCR_CTXPN                 3018
#define IDS_DESCR_OEM1                  3019
#define IDS_DESCR_OEM2                  3020
#define IDS_NONE_SELECTED               3100
#define IDS_PRIORITY_LOW                3200
#define IDS_PRIORITY_NORMAL             3201
#define IDS_PRIORITY_HIGH               3202
#define IDS_PRIORITY_VERYHIGH           3203
#define IDS_BWIDTH_NOLIMIT              3204
#define IDS_SELECT_NONE                 3205
#define IDS_TAB_ONE                     3206
#define IDS_TAB_TWO                     3207
#define IDS_TAB_THREE                   3208
#define IDC_VC_CONTROL_TEXT_MAX         3209
#define IDC_SESSION_LIMIT_MAX_TEXT      3210
#define IDS_SESS_BWIDTH_NOLIMIT         3211
#define IDC_LOGFILENAME                 3214
#define IDC_LOGGING_STATUS              3215
#define IDC_LOG_STATUS_LABEL            3217
#define IDC_LOG_FILENAME_LABEL          3218
#define IDS_DESCR_OEM3                  3221
#define IDS_DESCR_OEM4                  3222
#define IDS_DESCR_OEM5                  3223
#define IDS_DEFAULTLOGFILE              3224
#define IDS_LOGSTATUS_ON                3225
#define IDS_LOGSTATUS_OFF               3226
#define IDC_SESSION_C_DROP              1003
#define IDC_MSI_LABEL					1004
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         3219
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
